dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

install: true

before_install:
  - sudo apt-get -y install build-essential
  - go get github.com/mitchellh/gox

script:
  - gox -osarch="windows/amd64" -verbose -output="quler_windows_64"
  - mkdir quler_windows_64
  - cp app.example.conf quler_windows_64/app.conf
  - cp quler_windows_64.exe quler_windows_64/quler_windows_64.exe
  - cp -r result quler_windows_64/
  - zip -r quler_windows_64.zip quler_windows_64
  #########################################################
  - gox -osarch="windows/386" -verbose -output="quler_windows_86"
  - mkdir quler_windows_86
  - cp app.example.conf quler_windows_86/app.conf
  - cp quler_windows_86.exe quler_windows_86/quler_windows_86.exe
  - cp -r result quler_windows_86/
  - zip -r quler_windows_86.zip quler_windows_86
  #########################################################
  - gox -osarch="linux/amd64" -verbose -output="quler_linux_64"
  - mkdir quler_linux_64_x
  - cp app.example.conf quler_linux_64_x/app.conf
  - cp quler_linux_64 quler_linux_64_x/quler_linux_64
  - cp -r result quler_linux_64_x/
  - zip -r quler_linux_64.zip quler_linux_64_x

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - quler_windows_64.zip
  - quler_windows_86.zip
  - quler_linux_64.zip
  skip_cleanup: true
  on:
    tags: true