dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

install: true

before_install:
  - go get github.com/mitchellh/gox

script:
  - gox -osarch="windows/amd64" -verbose -output="quler_windows_64"
  - gox -osarch="windows/386" -verbose -output="quler_windows_86"
  - gox -osarch="linux/amd64" -verbose -output="quler_linux_64"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - quler_windows_64.exe
  - quler_windows_86.exe
  - quler_linux_64
  skip_cleanup: true
  on:
    tags: true